require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports only on local dev. The live VM runs RAILS_ENV=development
  # but is publicly reachable via Cloudflare tunnel — leaking a full Rails trace to a
  # member who triggers a 500 is an info-disclosure risk.
  config.consider_all_requests_local = ENV.fetch("APP_HOST", "localhost") == "localhost"

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # APP_HOST is the public hostname (e.g. via a Cloudflare tunnel) where the PWA is reachable.
  # Defaults to localhost for plain local dev; set it in .env when serving phones over HTTPS.
  app_host = ENV.fetch("APP_HOST", "localhost")
  app_protocol = app_host == "localhost" ? "http" : "https"

  # Allow the public hostname through host authorization.
  config.hosts << app_host

  # Use it for links generated in mailer templates AND for ActiveStorage redirect URLs.
  config.action_mailer.default_url_options = { host: app_host, protocol: app_protocol }
  Rails.application.routes.default_url_options = { host: app_host, protocol: app_protocol }

  # Resend SMTP for real magic-link delivery (the tunnel exposes the app to real phones).
  # If RESEND_API_KEY is unset, mails are no-op'd — pull magic-link tokens from the Rails
  # console instead. See README for the one-liner.
  if ENV["RESEND_API_KEY"].present?
    config.action_mailer.delivery_method = :smtp
    config.action_mailer.perform_deliveries = true
    config.action_mailer.raise_delivery_errors = true
    config.action_mailer.smtp_settings = {
      address:        "smtp.resend.com",
      port:           465,
      user_name:      "resend",
      password:       ENV["RESEND_API_KEY"],
      authentication: :plain,
      enable_starttls_auto: false,
      tls:            true
    }
  else
    config.action_mailer.delivery_method = :test
    config.action_mailer.perform_deliveries = false
  end

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Use Solid Queue for ActiveJob in development too — this VM runs RAILS_ENV=development
  # in production, and the default :async adapter loses every queued job on restart
  # (sign-in mailers, push notifications, scheduled tournament-start announces).
  # Tests override this to :test in test_helper.
  config.active_job.queue_adapter = :solid_queue

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
